version: "3.0"

services:
  drf:
    build: .
    container_name: drf
    command: gunicorn --bind 0.0.0.0:8000 RestAPIProject.wsgi
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - redis
      - celery
  redis:
    image: redis:6-alpine
    volumes:
      - redis_data:/data/
    expose:
      - 6379
  celery:
    build: .
    command: celery -A RestAPIProject worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
  nginx:
    build: ./nginx
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "80:80"
    depends_on:
      - drf

volumes:
  static_volume:
  media_volume:
  redis_data: