version: "3.0"

services:
  drf:
    build: .
    container_name: drf
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - redis
      - celery
  redis:
    image: redis:6-alpine
    volumes:
      - redis_data:/data/
    expose:
      - 6379
  celery:
    build: .
    command: celery -A RestAPIProject worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
volumes:
  static_volume:
  media_volume:
  redis_data: